name: Space Operation CI/CD & Security

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Ext_course_1440-Planner-task-8

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests
        run: gradle test

      - name: Run Trivy SAST scanner (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './Ext_course_1440'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Build Docker Compose Images
        env:
          MISSION_SECRET_KEY: ${{ secrets.MISSION_SECRET_KEY }}
        run: docker compose build

      - name: Run Trivy Image scanner on Server
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ext_course_1440-server:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'